[build]
dockerfilePath = "backend/Dockerfile"
dockerContextPath = "backend"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/equipment"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10